### ISSUE TITLE
declared variable close to it use

### ISSUE THREAD

**Issue by RicardoRodriguezArg** [Bazanero256/cpp-console-application-bootcamp#3]
https://github.com/Bazanero256/cpp-console-application-bootcamp/blob/5643871728997670619bec920e40b307938e7e5f/Practico2/Practico2/main.cpp#L22
Deberias declarar las variables cerca de donde vas a usarla, no antes.

**Comment by Bazanero256** [comment]
me tiraba error cuando las declaraba dentro del switch case, pruebo declararlas adentro para ver si el compilador me deja
