### ISSUE TITLE
implicit cast to bool

### ISSUE THREAD

**Issue by RicardoRodriguezArg** [Bazanero256/cpp-console-application-bootcamp#4]
https://github.com/Bazanero256/cpp-console-application-bootcamp/blob/5643871728997670619bec920e40b307938e7e5f/Practico2/Practico2/Operaciones_String.cpp#L7
std::string::compare() returns an int:
equal to zero if s and t are equal,
less than zero if s is less than t,
greater than zero if s is greater than t.

Use operator "==" which returns bool as result

**Comment by Bazanero256** [comment]
pero no es que string tiene el operador "==" sobrecargado? A lo mejor conviene devolver un int en vez de un entero?
